[workspace]

resolver = "2"
members = [
  "actor",
  "file_io",
  "image",
  "learner",
  "model",
  "mono",
  "packets",
  "ports",
  "priority_tree",
  "replay",
  "replay_data",
  "replay_memories",
  "replay_wrappers",
  "tcp_io",
]
