[package]
name = "replay_data"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.1.0", path = "../image" }
serde = { version = "1.0.171", features = ["derive"] }
zstd = "0.13.1"
