[package]
name = "packets"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { version = "0.1.0", path = "../model" }
replay_data = { version = "0.1.0", path = "../replay_data" }
serde = { version = "1.0.171", features = ["derive"] }
